spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users?serverTimezone=Europe/Minsk&useSSL=false
    username: root
    password: 4712VS5988_gh

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8081