spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 4712VS5988_gh

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8082
